"""Compose and run the 4-mecanum-wheel competition scene in Isaac Sim.

Builds on create_mobile_manipulator_scene.py but replaces the kinematic
diff-drive robot with the physics-articulated mecanum robot generated by
generate_mecanum_robot_urdf.py (Kaya-style passive sphere rollers at 45 deg).

The runtime bridge mirrors the REAL mecanum stack's ROS contract
(src/robot_hardware/robot_hardware/mecanum_bridge_node.py):
  subscribe /cmd_vel (+ /cmd_vel_direct > /cmd_vel > /cmd_vel_smoothed >
            /cmd_vel_nav priority mux, 0.5 s timeout, same as the old sim),
            /base/move_relative (String JSON {dx,dy,dyaw}), /safety/e_stop,
            /gripper/command (String OPEN/CLOSE), /mk1/gripper_joint_command
  publish  /odom/wheel (+ /chassis/odom alias), /joint_states, /motor/state
           (String JSON, drive_type=mecanum), /base/move_result, /clock,
           /laser_scan (re-stamped from the Isaac lidar raw topic), TF
           odom->base_link, /sim/ground_truth_pose (String JSON).

Wheel command mixing uses the repo's own MecanumKinematics so the sim
exercises the exact IK/FK the real robot runs.

Drive modes:
  --drive-mode physics   (default) velocity drives on the 4 wheel joints;
                         the mecanum behaviour emerges from roller contact.
  --drive-mode kinematic fallback: integrates the commanded body twist and
                         teleports the (kinematic) root, like the old
                         diff-drive sim bridge but holonomic.
"""

from __future__ import annotations

import argparse
import json
import math
import os
import shutil
import sys
import time
from pathlib import Path

from isaacsim import SimulationApp

REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPTS_DIR = Path(__file__).resolve().parent
# stadium_competition_grid42.usd follows the 2026-07-06 grid placement rule
# (28 objects on a random 28 of the 42 official 50 cm grid points, seed 14).
# Regenerate variants with generate_competition_stadium_layout.py --layout grid42.
DEFAULT_STADIUM = REPO_ROOT / "simulation" / "usd" / "stadium_competition_grid42.usd"
DEFAULT_URDF = REPO_ROOT / "hardware" / "cad" / "urdf" / "robot_mk3_mecanum_sim.urdf"
DEFAULT_USD_DIR = REPO_ROOT / "simulation" / "usd" / "robot_mk3_mecanum_sim"
DEFAULT_SCENE = REPO_ROOT / "simulation" / "usd" / "mecanum_competition_scene.usda"
DEFAULT_PROOF = Path("/tmp/team14_mecanum_competition_scene.json")
DEFAULT_ROS_DISTRO = "humble"
SUPPORTED_ROS_DISTROS = ("humble", "jazzy")

sys.path.insert(0, str(REPO_ROOT / "src" / "robot_hardware"))
from robot_hardware.mecanum_control import (  # noqa: E402
    WHEEL_NAMES,
    MecanumKinematics,
)

ROBOT_ROOT = "/World/mecanum_robot"
ROBOT_DEFAULT_PRIM = "robot_mk3_mecanum_sim"
# Competition start zone is the bottom-right 40x40 cm; strategy holds yaw at
# +90 deg (facing the grid). URDF is authored +Y forward => -90 deg USD offset.
# The stadium floor slab top is at z=0.05; spawn just above it.
START_XYZ = (1.8, -1.8, 0.052)
START_YAW_DEG = 90.0
USD_VISUAL_YAW_OFFSET_DEG = -90.0

BASE_FRAME = "base_link"
ODOM_FRAME = "odom"
ODOM_TOPIC = "/odom/wheel"
ODOM_ALIAS_TOPIC = "/chassis/odom"
MOTOR_STATE_TOPIC = "/motor/state"
MOVE_RELATIVE_TOPIC = "/base/move_relative"
MOVE_RESULT_TOPIC = "/base/move_result"
E_STOP_TOPIC = "/safety/e_stop"
GROUND_TRUTH_TOPIC = "/sim/ground_truth_pose"
OBJECTS_STATE_TOPIC = "/sim/objects_state"
# Official storage zone in map frame; an object "scores" only if, seen from
# above, it lies fully inside the rim (2026-07-07 judge clarification).
STORAGE_ZONE = (-2.0, -1.6, -2.0, -1.6)  # xmin, xmax, ymin, ymax
OBJECT_HALF_EXTENT_M = 0.04  # 8 cm objects
GRIPPER_STRING_TOPIC = "/gripper/command"
GRIPPER_STATE_TOPIC = "/gripper/state"

CMD_VEL_TOPIC = "/cmd_vel"
CMD_VEL_NAV_TOPIC = "/cmd_vel_nav"
CMD_VEL_DIRECT_TOPIC = "/cmd_vel_direct"
CMD_VEL_SMOOTHED_TOPIC = "/cmd_vel_smoothed"
CMD_SOURCE_TIMEOUT_SEC = 0.5
CMD_SOURCE_PRIORITY = (
    CMD_VEL_DIRECT_TOPIC,
    CMD_VEL_TOPIC,
    CMD_VEL_SMOOTHED_TOPIC,
    CMD_VEL_NAV_TOPIC,
)

# Drive geometry defaults: mirror src/robot_bringup/config/real.yaml
# mecanum_bridge_node section. Overridden at startup from the mecanum_*
# attributes authored in the generated URDF (see load_urdf_geometry), so the
# 68 mm vs 80 mm purchased-wheel variants stay consistent automatically.
WHEEL_RADIUS_M = 0.034
HALF_LENGTH_M = 0.150
HALF_WIDTH_M = 0.125
MAX_LINEAR_X_MPS = 0.24
MAX_LINEAR_Y_MPS = 0.20
MAX_ANGULAR_RPS = 0.80
MAX_WHEEL_RAD_S = 12.0
# URDF wheel joints spin about +X (robot right); positive joint velocity moves
# the robot backward, so IK outputs need a -1 sign on every wheel.
WHEEL_JOINT_SIGNS = (-1.0, -1.0, -1.0, -1.0)
WHEEL_DOF_NAMES = tuple(f"{name}_wheel_spin" for name in WHEEL_NAMES)

GRIPPER_OPEN_TRAVEL_M = 0.045
GRIPPER_COMMAND_TOPIC = "/mk1/gripper_joint_command"
FINGER_DOF_NAMES = ("left_finger_slide", "right_finger_slide")

# --- Synthetic D435i IMU (Bosch BMI055) --------------------------------
# Matches the real sensor's datasheet behaviour as closely as the sim loop
# allows: the publish rate is the sim loop rate (~30-60 Hz vs the real
# 200/400 Hz gyro), so per-sample white noise is scaled by the actual dt
# (sigma = density * sqrt(1/(2*dt))). Only gyro-z is consumed by the
# localizer; accel is published for completeness (gravity included).
IMU_TOPIC = "/imu/d435i"
IMU_GYRO_NOISE_DENSITY_RAD = math.radians(0.014)  # BMI055: 0.014 dps/sqrt(Hz)
# In-run zero-rate stability AFTER the boot-time stationary calibration the
# real firmware performs (raw BMI055 offset is +-1 dps, but drivers zero it).
IMU_GYRO_BIAS_RAD_S = math.radians(0.05)
IMU_GYRO_RANGE_RAD_S = math.radians(2000.0)       # +-2000 dps
IMU_ACCEL_NOISE_DENSITY = 190e-6 * 9.81           # 190 ug/sqrt(Hz)
IMU_ACCEL_RANGE = 4.0 * 9.81                      # RealSense default +-4 g

MOVE_RELATIVE_MAX_LINEAR_MPS = 0.18
MOVE_RELATIVE_MAX_ANGULAR_RPS = 1.5  # in-place mecanum spin: wheel 1.5*0.22/0.04 = 8.3 rad/s << motor 35
MOVE_RELATIVE_XY_TOLERANCE_M = 0.01
MOVE_RELATIVE_YAW_TOLERANCE_RAD = 0.02
MOVE_RELATIVE_TIMEOUT_SEC = 35.0  # wall-time stall guard; long street legs at low RTF need headroom
# P-gain also sets the decel tail: time-to-tolerance ~ ln(v/(gain*tol))/gain,
# ~1.3 s per move at 2.5 vs ~0.5 s at 5.0 - across ~10 moves/object that is
# most of the surrogate's overhead. Kinematic mode has no dynamics to
# destabilize; the real firmware runs its own trapezoid profile instead.
MOVE_RELATIVE_GAIN = 5.0
# Physics mode has real inertia + roller slip: gain 5 would ring around the
# 1 cm tolerance. Softer gain, and a slightly wider tolerance to absorb the
# contact jitter of the passive rollers at rest.
MOVE_RELATIVE_GAIN_PHYSICS = 2.0
MOVE_RELATIVE_XY_TOLERANCE_PHYSICS_M = 0.02

PHYSICS_HZ = 240.0
KINEMATIC_MAX_DT = 0.05

LIDAR_TOPIC = "/laser_scan"
LIDAR_RAW_TOPIC = "/laser_scan_raw"
LIDAR_FRAME = "base_link"

# --demo showcase: (label, (vx, vy, wz), sim-seconds). vy phases are the
# mecanum-specific lateral moves.
DEMO_SEQUENCE = (
    ("forward +vx", (0.20, 0.0, 0.0), 3.0),
    ("stop", (0.0, 0.0, 0.0), 1.0),
    ("strafe left +vy", (0.0, 0.18, 0.0), 4.0),
    ("strafe right -vy", (0.0, -0.18, 0.0), 4.0),
    ("diagonal +vx+vy", (0.14, 0.14, 0.0), 3.0),
    ("diagonal -vx-vy", (-0.14, -0.14, 0.0), 3.0),
    ("rotate CCW +wz", (0.0, 0.0, 0.8), 3.0),
    ("rotate CW -wz", (0.0, 0.0, -0.8), 3.0),
    ("backward -vx", (-0.20, 0.0, 0.0), 3.0),
    ("stop", (0.0, 0.0, 0.0), 1.5),
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--stadium", default=str(DEFAULT_STADIUM), help="Input stadium USD stage.")
    parser.add_argument("--urdf", default=str(DEFAULT_URDF), help="Input mecanum robot URDF.")
    parser.add_argument("--usd-dir", default=str(DEFAULT_USD_DIR), help="Directory for imported robot USD assets.")
    parser.add_argument("--scene", default=str(DEFAULT_SCENE), help="Output composed scene USD.")
    parser.add_argument("--proof-path", default=str(DEFAULT_PROOF), help="JSON proof output path.")
    parser.add_argument(
        "--ros-distro",
        choices=SUPPORTED_ROS_DISTROS,
        default=DEFAULT_ROS_DISTRO,
        help="ROS 2 distro for the Isaac ROS2 bridge environment (default humble).",
    )
    parser.add_argument(
        "--drive-mode",
        choices=("physics", "kinematic"),
        default="physics",
        help="physics: roller-contact articulation; kinematic: integrate twist, teleport root.",
    )
    parser.add_argument("--headless", action="store_true", help="Run Isaac Sim headless.")
    parser.add_argument("--run", action="store_true", help="Play the scene and run the ROS bridge loop.")
    parser.add_argument(
        "--no-cameras",
        action="store_true",
        help="Skip the RGB/depth camera publishers (biggest render cost); lidar-only runs are much closer to real time.",
    )
    parser.add_argument(
        "--demo",
        action="store_true",
        help=(
            "Scripted motion showcase (forward/strafe/diagonal/rotate) driven "
            "directly through the wheel IK inside the sim process - no ROS "
            "node is created, so it cannot interfere with DDS traffic."
        ),
    )
    parser.add_argument(
        "--speed-scale",
        type=float,
        default=1.0,
        help=(
            "Multiplier on the bridge velocity caps (linear x/y, angular, wheel). "
            "Use 1.5 to model the JGB37-520 motor swap (>=1.5x faster wheels)."
        ),
    )
    parser.add_argument(
        "--camera-z-offset",
        type=float,
        default=0.0,
        help="Raise both D435 cameras by this many meters (mount height experiments).",
    )
    parser.add_argument(
        "--snapshot-period",
        type=float,
        default=3.0,
        help="Sim-seconds between annotated top-view progress snapshots (0 disables). Saved to logs/match_snapshots/<stamp>/.",
    )
    parser.add_argument("--run-seconds", type=float, default=0.0, help="Auto-exit after N seconds of --run (0 = forever).")
    parser.add_argument("--overwrite", action="store_true", help="Overwrite existing generated robot USD directory.")
    return parser.parse_args()


def require_path(path: Path, label: str) -> None:
    if not path.exists():
        raise FileNotFoundError(f"{label} not found: {path}")


def load_urdf_geometry(urdf: Path) -> None:
    """Adopt wheel geometry from the generated URDF's mecanum_* attributes."""
    import xml.etree.ElementTree as ET

    global WHEEL_RADIUS_M, HALF_LENGTH_M, HALF_WIDTH_M
    root = ET.parse(str(urdf)).getroot()
    radius = root.get("mecanum_wheel_radius_m")
    half_length = root.get("mecanum_half_length_m")
    half_width = root.get("mecanum_half_width_m")
    if radius:
        WHEEL_RADIUS_M = float(radius)
    if half_length:
        HALF_LENGTH_M = float(half_length)
    if half_width:
        HALF_WIDTH_M = float(half_width)


def usd_asset_path(path: Path, relative_to: Path | None = None) -> str:
    if relative_to is not None:
        path = Path(os.path.relpath(path, start=relative_to))
    return str(path).replace("\\", "/")


def write_composed_scene(scene: Path, stadium: Path, robot_usd: Path, kinematic_root: bool) -> None:
    scene_dir = scene.parent
    root_flags = [
        f"        double3 xformOp:translate = ({START_XYZ[0]}, {START_XYZ[1]}, {START_XYZ[2]})",
        f"        double xformOp:rotateZ = {START_YAW_DEG + USD_VISUAL_YAW_OFFSET_DEG}",
        '        uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:rotateZ"]',
    ]
    if kinematic_root:
        robot_def = [
            f'    def Xform "{ROBOT_ROOT.rsplit("/", 1)[-1]}" (',
            '        prepend apiSchemas = ["PhysicsRigidBodyAPI"]',
            f"        prepend references = @{usd_asset_path(robot_usd, scene_dir)}@</{ROBOT_DEFAULT_PRIM}>",
            "    )",
            "    {",
            "        bool physics:kinematicEnabled = true",
            "        bool physics:rigidBodyEnabled = true",
            *root_flags,
            "    }",
        ]
    else:
        robot_def = [
            f'    def Xform "{ROBOT_ROOT.rsplit("/", 1)[-1]}" (',
            f"        prepend references = @{usd_asset_path(robot_usd, scene_dir)}@</{ROBOT_DEFAULT_PRIM}>",
            "    )",
            "    {",
            *root_flags,
            "    }",
        ]

    scene.write_text(
        "\n".join(
            [
                "#usda 1.0",
                "(",
                '    defaultPrim = "World"',
                "    metersPerUnit = 1",
                '    upAxis = "Z"',
                "    subLayers = [",
                f"        @{usd_asset_path(stadium, scene_dir)}@,",
                "    ]",
                ")",
                "",
                'def "Looks"',
                "{",
                '    def DistantLight "KeyLight"',
                "    {",
                "        float inputs:intensity = 450.0",
                "        float inputs:angle = 0.35",
                "        double3 xformOp:rotateXYZ = (-45, 0, 35)",
                '        uniform token[] xformOpOrder = ["xformOp:rotateXYZ"]',
                "    }",
                "",
                '    def DomeLight "FillLight"',
                "    {",
                "        float inputs:intensity = 180.0",
                "        color3f inputs:color = (1, 1, 1)",
                "    }",
                "",
                '    def Material "WoodFloor"',
                "    {",
                '        token outputs:surface.connect = </Looks/WoodFloor/Shader.outputs:surface>',
                '        def Shader "Shader"',
                "        {",
                '            uniform token info:implementationSource = "sourceAsset"',
                '            asset info:mdl:sourceAsset = @OmniPBR.mdl@',
                '            token info:mdl:sourceAsset:subIdentifier = "OmniPBR"',
                # OmniPBR exposes *_constant names; the bare names silently
                # fail to bind (MDL warnings) and the floor rendered gray.
                # Procedural plywood texture (repo asset) for realistic wood
                # grain instead of a flat tone.
                '            asset inputs:diffuse_texture = @../assets/plywood_floor.png@',
                '            color3f inputs:diffuse_color_constant = (0.72, 0.52, 0.30)',
                '            color3f inputs:diffuse_tint = (1.0, 1.0, 1.0)',
                '            float inputs:reflection_roughness_constant = 0.82',
                '            float inputs:metallic_constant = 0.0',
                '            token outputs:surface',
                "        }",
                "    }",
                "}",
                "",
                "# Disable legacy MK1 action graphs authored in the stadium layer.",
                'over "Graph" (',
                "    active = false",
                ")",
                "{",
                "}",
                "",
                'over "World"',
                "{",
                '    over "floor"',
                "    {",
                '        rel material:binding = </Looks/WoodFloor>',
                "    }",
                "",
                '    over "mk1" (',
                "        active = false",
                "    )",
                "    {",
                "    }",
                "",
                "    # The competition stage embeds the old diff-drive robot; disable it.",
                '    over "team14_robot_mk2_simplified" (',
                "        active = false",
                "    )",
                "    {",
                "    }",
                "",
                *robot_def,
                "}",
                "",
            ]
        ),
        encoding="utf-8",
    )


def tune_physics(scene: Path, app: SimulationApp) -> dict[str, object]:
    """Raise the physics rate and prep roller contacts for the tiny wheels."""

    import omni.usd
    from pxr import Gf, Sdf, UsdGeom, UsdPhysics, UsdShade, PhysxSchema

    context = omni.usd.get_context()
    if not context.open_stage(str(scene)):
        raise RuntimeError(f"Failed to open generated scene for physics tuning: {scene}")
    for _ in range(30):
        app.update()
    stage = context.get_stage()
    if stage is None:
        raise RuntimeError("No USD stage is available for physics tuning.")
    stage.SetEditTarget(stage.GetRootLayer())

    # Physics scene: find or create, then raise the step rate.
    scene_prim = None
    for prim in stage.Traverse():
        if prim.IsA(UsdPhysics.Scene):
            scene_prim = prim
            break
    if scene_prim is None:
        scene_prim = UsdPhysics.Scene.Define(stage, "/World/physicsScene").GetPrim()
    physx_scene = PhysxSchema.PhysxSceneAPI.Apply(scene_prim)
    physx_scene.CreateTimeStepsPerSecondAttr(PHYSICS_HZ)
    physx_scene.CreateSolverTypeAttr("TGS")
    # CPU dynamics is markedly more stable for the tiny roller contacts.
    physx_scene.CreateEnableGPUDynamicsAttr(False)

    # High-friction physics material for the rollers and the floor.
    material_path = "/World/Physics/RollerMaterial"
    material = UsdShade.Material.Define(stage, material_path)
    physics_material = UsdPhysics.MaterialAPI.Apply(material.GetPrim())
    physics_material.CreateStaticFrictionAttr(1.1)
    physics_material.CreateDynamicFrictionAttr(1.0)
    physics_material.CreateRestitutionAttr(0.0)

    roller_count = 0
    joint_armature_count = 0
    robot_prim = stage.GetPrimAtPath(ROBOT_ROOT)
    if not robot_prim.IsValid():
        raise RuntimeError(f"Missing robot prim for physics tuning: {ROBOT_ROOT}")
    for prim in stage.Traverse():
        path = str(prim.GetPath())
        if not path.startswith(ROBOT_ROOT):
            continue
        if "_roller_" in path and (prim.HasAPI(UsdPhysics.CollisionAPI) or prim.IsA(UsdGeom.Sphere)):
            physx_collision = PhysxSchema.PhysxCollisionAPI.Apply(prim)
            physx_collision.CreateContactOffsetAttr(0.003)
            physx_collision.CreateRestOffsetAttr(0.0)
            binding = UsdShade.MaterialBindingAPI.Apply(prim)
            binding.Bind(material, UsdShade.Tokens.weakerThanDescendants, "physics")
            roller_count += 1
        # Joint armature damps the tiny roller/wheel joints against contact
        # impulse jitter (standard Isaac stabilization for small wheels).
        if prim.IsA(UsdPhysics.RevoluteJoint):
            name = prim.GetName()
            if "_roller_" in name or name.endswith("_wheel_spin"):
                joint_api = PhysxSchema.PhysxJointAPI.Apply(prim)
                joint_api.CreateArmatureAttr(1.0e-4 if "_roller_" in name else 1.0e-3)
                joint_armature_count += 1

    # Articulation solver budget for the many-contact roller sim.
    for prim in [robot_prim, *robot_prim.GetChildren()]:
        if prim.HasAPI(UsdPhysics.ArticulationRootAPI):
            articulation = PhysxSchema.PhysxArticulationAPI.Apply(prim)
            articulation.CreateSolverPositionIterationCountAttr(32)
            articulation.CreateSolverVelocityIterationCountAttr(4)

    root_layer = stage.GetRootLayer()
    if not root_layer.Save():
        raise RuntimeError(f"Failed to save physics tuning to {root_layer.identifier}")
    for _ in range(10):
        app.update()
    return {
        "physics_hz": PHYSICS_HZ,
        "roller_collisions_tuned": roller_count,
        "joint_armatures_set": joint_armature_count,
        "material": material_path,
    }


def normalize_angle(angle: float) -> float:
    return math.atan2(math.sin(angle), math.cos(angle))


def configure_mecanum_lidar(scene: Path, app: SimulationApp, parent_prim: str, translation, yaw_deg: float) -> dict[str, object]:
    """Create the PhysX lidar + ROS graph, parented to an explicit link prim.

    Unlike the mk2 helper (hardcoded base offsets), the sensor is attached to
    the URDF lidar link: a small rigid body whose CoM coincides with its
    frame, so the PhysX sensor pose is not skewed by the chassis CoM frame.
    """
    import omni.graph.core as og
    import omni.kit.commands
    import omni.usd
    import usdrt.Sdf
    from isaacsim.core.utils.extensions import enable_extension
    from pxr import Gf, UsdGeom

    enable_extension("isaacsim.sensors.physx")
    enable_extension("isaacsim.ros2.bridge")
    for _ in range(20):
        app.update()

    context = omni.usd.get_context()
    if not context.open_stage(str(scene)):
        raise RuntimeError(f"Failed to open generated scene for lidar graph setup: {scene}")
    for _ in range(60):
        app.update()
    stage = context.get_stage()
    stage.SetEditTarget(stage.GetRootLayer())

    lidar_prim_path = f"{parent_prim}/Lidar_PhysX"
    if stage.GetPrimAtPath(lidar_prim_path).IsValid():
        stage.RemovePrim(lidar_prim_path)

    _, lidar_schema = omni.kit.commands.execute(
        "RangeSensorCreateLidar",
        path="/Lidar_PhysX",
        parent=parent_prim,
        translation=Gf.Vec3d(*translation),
        orientation=Gf.Rotation(Gf.Vec3d(0.0, 0.0, 1.0), yaw_deg).GetQuat(),
        min_range=0.05,
        max_range=3.5,
        draw_points=False,
        draw_lines=False,
        horizontal_fov=360.0,
        vertical_fov=0.1,
        # 1.0 deg = 360 rays/step: halves raycast cost; wall_range uses only
        # ~24 beams so localization quality is unaffected.
        horizontal_resolution=1.0,
        vertical_resolution=0.1,
        # 0 = full 360 sweep every physics step. A nonzero rate makes PhysX
        # sweep progressively per step, and the LaserScan publisher stamps
        # those partial sweeps with full-circle angle metadata (directions
        # come out compressed/duplicated).
        rotation_rate=0.0,
        high_lod=False,
        yaw_offset=0.0,
        enable_semantics=False,
    )
    lidar_path = str(lidar_schema.GetPrim().GetPath())

    graph_path = "/World/ROS_Lidar_PhysX"
    if stage.GetPrimAtPath(graph_path).IsValid():
        stage.RemovePrim(graph_path)

    keys = og.Controller.Keys
    graph, _, _, _ = og.Controller.edit(
        {"graph_path": graph_path, "evaluator_name": "execution"},
        {
            keys.CREATE_NODES: [
                ("OnPlaybackTick", "omni.graph.action.OnPlaybackTick"),
                ("Context", "isaacsim.ros2.bridge.ROS2Context"),
                ("ReadSimTime", "isaacsim.core.nodes.IsaacReadSimulationTime"),
                ("ReadLidar", "isaacsim.sensors.physx.IsaacReadLidarBeams"),
                ("LaserScanPublisher", "isaacsim.ros2.bridge.ROS2PublishLaserScan"),
            ],
            keys.SET_VALUES: [
                ("Context.inputs:useDomainIDEnvVar", True),
                ("ReadSimTime.inputs:resetOnStop", False),
                ("ReadLidar.inputs:lidarPrim", [usdrt.Sdf.Path(lidar_path)]),
                ("LaserScanPublisher.inputs:frameId", LIDAR_FRAME),
                ("LaserScanPublisher.inputs:topicName", LIDAR_RAW_TOPIC),
                ("LaserScanPublisher.inputs:nodeNamespace", ""),
            ],
            keys.CONNECT: [
                ("OnPlaybackTick.outputs:tick", "ReadLidar.inputs:execIn"),
                ("ReadLidar.outputs:execOut", "LaserScanPublisher.inputs:execIn"),
                ("ReadLidar.outputs:azimuthRange", "LaserScanPublisher.inputs:azimuthRange"),
                ("ReadLidar.outputs:depthRange", "LaserScanPublisher.inputs:depthRange"),
                ("ReadLidar.outputs:horizontalFov", "LaserScanPublisher.inputs:horizontalFov"),
                ("ReadLidar.outputs:horizontalResolution", "LaserScanPublisher.inputs:horizontalResolution"),
                ("ReadLidar.outputs:intensitiesData", "LaserScanPublisher.inputs:intensitiesData"),
                ("ReadLidar.outputs:linearDepthData", "LaserScanPublisher.inputs:linearDepthData"),
                ("ReadLidar.outputs:numCols", "LaserScanPublisher.inputs:numCols"),
                ("ReadLidar.outputs:numRows", "LaserScanPublisher.inputs:numRows"),
                ("ReadLidar.outputs:rotationRate", "LaserScanPublisher.inputs:rotationRate"),
                ("Context.outputs:context", "LaserScanPublisher.inputs:context"),
                ("ReadSimTime.outputs:simulationTime", "LaserScanPublisher.inputs:timeStamp"),
            ],
        },
    )
    og.Controller.evaluate_sync(graph)

    root_layer = stage.GetRootLayer()
    if not root_layer.Save():
        raise RuntimeError(f"Failed to save lidar graph changes to {root_layer.identifier}")
    for _ in range(10):
        app.update()
    return {
        "lidar_prim": lidar_path,
        "parent": parent_prim,
        "graph": graph_path,
        "scan_topic": LIDAR_TOPIC,
        "raw_scan_topic": LIDAR_RAW_TOPIC,
        "frame_id": LIDAR_FRAME,
    }




class MecanumSimBridge:
    """ROS 2 bridge mirroring mecanum_bridge_node against the sim robot."""

    def __init__(self, stage, drive_mode: str):
        import rclpy
        from geometry_msgs.msg import TransformStamped, Twist
        from nav_msgs.msg import Odometry
        from rosgraph_msgs.msg import Clock
        from sensor_msgs.msg import Imu, JointState, LaserScan
        from std_msgs.msg import Bool, String
        from tf2_ros import TransformBroadcaster
        import omni.timeline

        if not rclpy.ok():
            rclpy.init(args=None)

        self.rclpy = rclpy
        self.Twist = Twist
        self.TransformStamped = TransformStamped
        self.Odometry = Odometry
        self.Clock = Clock
        self.JointState = JointState
        self.LaserScan = LaserScan
        self.String = String
        self.timeline = omni.timeline.get_timeline_interface()
        self.stage = stage
        self.drive_mode = drive_mode
        self.kinematics = MecanumKinematics(WHEEL_RADIUS_M, HALF_LENGTH_M, HALF_WIDTH_M)

        self.robot_prim = stage.GetPrimAtPath(ROBOT_ROOT)
        if not self.robot_prim.IsValid():
            raise RuntimeError(f"Missing robot prim: {ROBOT_ROOT}")

        self.articulation = None
        self.wheel_dof_indices = None
        self.finger_dof_indices = None

        self.node = rclpy.create_node("mecanum_isaac_sim_bridge")
        self.odom_pub = self.node.create_publisher(Odometry, ODOM_TOPIC, 20)
        self.odom_alias_pub = self.node.create_publisher(Odometry, ODOM_ALIAS_TOPIC, 20)
        self.clock_pub = self.node.create_publisher(Clock, "/clock", 20)
        self.joint_pub = self.node.create_publisher(JointState, "/joint_states", 20)
        self.scan_pub = self.node.create_publisher(LaserScan, LIDAR_TOPIC, 20)
        self.motor_state_pub = self.node.create_publisher(String, MOTOR_STATE_TOPIC, 10)
        self.move_result_pub = self.node.create_publisher(String, MOVE_RESULT_TOPIC, 10)
        self.ground_truth_pub = self.node.create_publisher(String, GROUND_TRUTH_TOPIC, 10)
        self.objects_state_pub = self.node.create_publisher(String, OBJECTS_STATE_TOPIC, 10)
        self._objects_state_last_pub = 0.0
        self.gripper_state_pub = self.node.create_publisher(String, GRIPPER_STATE_TOPIC, 10)
        self.Imu = Imu
        self.imu_pub = self.node.create_publisher(Imu, IMU_TOPIC, 50)
        import random as _random

        self._imu_gyro_bias = _random.uniform(-IMU_GYRO_BIAS_RAD_S, IMU_GYRO_BIAS_RAD_S)
        self._imu_rand = _random.Random()
        self._imu_prev = None  # (sim_time, yaw, vx_world, vy_world)
        self.tf_broadcaster = TransformBroadcaster(self.node)

        for topic in CMD_SOURCE_PRIORITY:
            self.node.create_subscription(
                Twist, topic, (lambda t: (lambda msg: self._cmd_callback(msg, t)))(topic), 10
            )
        self.node.create_subscription(String, MOVE_RELATIVE_TOPIC, self._move_relative_callback, 10)
        # Runtime lighting control for perception robustness sweeps:
        # {"key": 450, "fill": 180, "color": [1.0, 0.9, 0.8]}
        self.node.create_subscription(String, "/sim/lighting", self._lighting_callback, 10)
        self.node.create_subscription(Bool, E_STOP_TOPIC, self._e_stop_callback, 10)
        self.node.create_subscription(String, GRIPPER_STRING_TOPIC, self._gripper_string_callback, 10)
        self.node.create_subscription(JointState, GRIPPER_COMMAND_TOPIC, self._gripper_joint_callback, 10)
        self.node.create_subscription(LaserScan, LIDAR_RAW_TOPIC, self._scan_callback, 10)
        self.node.create_subscription(String, "/match/state", self._match_state_callback, 10)
        self.match_state = "IDLE"
        # Top-view progress snapshots every N sim-seconds (0 disables).
        self.snapshot_period = 0.0
        self.snapshot_dir: Path | None = None
        self._next_snapshot_time = 0.0
        self._pending_annotations: list[tuple[Path, str, str]] = []
        self._snapshot_camera_ready = False

        # Odometry state (wheel-integrated, like the real bridge).
        self.x = float(START_XYZ[0])
        self.y = float(START_XYZ[1])
        self.yaw = math.radians(START_YAW_DEG)
        self.wheel_positions = [0.0, 0.0, 0.0, 0.0]
        self.wheel_velocities = [0.0, 0.0, 0.0, 0.0]

        self.cmd_by_source: dict[str, tuple[float, float, float, float]] = {}
        self.commanded_twist = (0.0, 0.0, 0.0)
        self.e_stop = False
        self.gripper_travel = GRIPPER_OPEN_TRAVEL_M
        self.move_target = None  # (target_x, target_y, target_yaw, start_time)
        self.sim_time = float(self.timeline.get_current_time())
        self.last_wall = time.monotonic()
        self._motor_state_last_pub = 0.0

    def attach_articulation(self):
        if self.drive_mode != "physics":
            return
        from isaacsim.core.experimental.prims import Articulation

        self.articulation = Articulation(ROBOT_ROOT)
        self.wheel_dof_indices = self.articulation.get_dof_indices(list(WHEEL_DOF_NAMES))
        self.finger_dof_indices = self.articulation.get_dof_indices(list(FINGER_DOF_NAMES))

    # --- callbacks -------------------------------------------------------
    def _cmd_callback(self, msg, source: str):
        now = time.monotonic()
        vx = float(msg.linear.x)
        vy = float(msg.linear.y)
        wz = float(msg.angular.z)
        if not all(math.isfinite(v) for v in (vx, vy, wz)):
            vx = vy = wz = 0.0
        vx = max(min(vx, MAX_LINEAR_X_MPS), -MAX_LINEAR_X_MPS)
        vy = max(min(vy, MAX_LINEAR_Y_MPS), -MAX_LINEAR_Y_MPS)
        wz = max(min(wz, MAX_ANGULAR_RPS), -MAX_ANGULAR_RPS)
        self.cmd_by_source[source] = (vx, vy, wz, now)
        # A nonzero manual twist preempts an active relative move (real
        # bridge behaviour).
        if self.move_target is not None and (abs(vx) > 1e-4 or abs(vy) > 1e-4 or abs(wz) > 1e-4):
            self._finish_move(ok=False, reason="preempted_by_cmd_vel")

    def _select_cmd(self, now: float) -> tuple[float, float, float]:
        for source in CMD_SOURCE_PRIORITY:
            command = self.cmd_by_source.get(source)
            if command is None:
                continue
            vx, vy, wz, stamp = command
            if now - stamp <= CMD_SOURCE_TIMEOUT_SEC:
                return vx, vy, wz
        return 0.0, 0.0, 0.0

    def _move_relative_callback(self, msg):
        try:
            payload = json.loads(msg.data)
            dx = float(payload.get("dx", 0.0))
            dy = float(payload.get("dy", 0.0))
            dyaw = float(payload.get("dyaw", 0.0))
        except (ValueError, TypeError) as exc:
            self._publish_move_result(ok=False, reason=f"bad_json:{exc}")
            return
        if self.move_target is not None:
            self._publish_move_result(ok=False, reason="busy")
            return
        cos_yaw = math.cos(self.yaw)
        sin_yaw = math.sin(self.yaw)
        target_x = self.x + dx * cos_yaw - dy * sin_yaw
        target_y = self.y + dx * sin_yaw + dy * cos_yaw
        target_yaw = normalize_angle(self.yaw + dyaw)
        self.move_target = (target_x, target_y, target_yaw, time.monotonic())
        self._move_progress = None  # restart the stall guard for this move
        try:
            self.move_speed_cap = float(payload.get("max_v")) if payload.get("max_v") else None
        except (TypeError, ValueError):
            self.move_speed_cap = None

    def _lighting_callback(self, msg):
        try:
            payload = json.loads(msg.data)
        except (ValueError, TypeError):
            return
        from pxr import Gf

        for path, key in (("/Looks/KeyLight", "key"), ("/Looks/FillLight", "fill")):
            prim = self.stage.GetPrimAtPath(path)
            if not prim.IsValid():
                continue
            if key in payload:
                prim.GetAttribute("inputs:intensity").Set(float(payload[key]))
            if key == "fill" and "color" in payload:
                r, g, b = (float(v) for v in payload["color"][:3])
                prim.GetAttribute("inputs:color").Set(Gf.Vec3f(r, g, b))
        self.node.get_logger().info(f"lighting set: {payload}")

    def _e_stop_callback(self, msg):
        self.e_stop = bool(msg.data)
        if self.e_stop:
            self.cmd_by_source.clear()
            if self.move_target is not None:
                self._finish_move(ok=False, reason="e_stop")

    def _gripper_string_callback(self, msg):
        command = str(msg.data).strip().upper()
        if command.startswith("OPEN"):
            self.gripper_travel = GRIPPER_OPEN_TRAVEL_M
            self._release_object()
        elif command.startswith("CLOSE"):
            self.gripper_travel = 0.0
            self._try_grab_object()

    # --- cheat-grip: attach the nearest competition object on CLOSE ------
    # Physical finger grasping of the printed objects is out of scope for the
    # strategy rehearsal; CLOSE latches the nearest object within reach to the
    # gripper (kinematic follow), OPEN releases it in place.
    # Grip zone modeled on the REAL parallel gripper (not a radius): fingers
    # span x in [0.095, 0.245] ahead of base center (10cm finger length from
    # the 0.145 gripper point +-), tips open to +-0.1025 so an 8cm object
    # must sit within +-0.06 laterally to be enclosed.
    GRIP_ZONE_FWD_MIN_M = 0.095
    GRIP_ZONE_FWD_MAX_M = 0.245
    GRIP_ZONE_LAT_M = 0.06
    GRIP_FORWARD_OFFSET_M = 0.145
    GRIP_CARRY_HEIGHT_M = 0.12

    def _gripper_world_point(self) -> tuple[float, float]:
        gt = self._ground_truth_pose()
        if gt is None:
            return self.x, self.y
        x, y, yaw = gt
        return (
            x + math.cos(yaw) * self.GRIP_FORWARD_OFFSET_M,
            y + math.sin(yaw) * self.GRIP_FORWARD_OFFSET_M,
        )

    def _object_center(self, prim) -> tuple[float, float]:
        """World XY of the object's geometry center.

        The pivotFix bake puts the GEOMETRY on the grid point but moves the
        prim frame origin the other way (banana: 0.5m!), so the offset from
        origin to bbox center is measured ONCE per prim and cached."""
        import omni.usd
        from pxr import Usd, UsdGeom

        if not hasattr(self, "_center_offsets"):
            self._center_offsets = {}
        path = str(prim.GetPath())
        matrix = omni.usd.get_world_transform_matrix(prim)
        t = matrix.ExtractTranslation()
        if path not in self._center_offsets:
            cache = UsdGeom.BBoxCache(Usd.TimeCode.Default(), ["default", "render"])
            box = cache.ComputeWorldBound(prim).ComputeAlignedRange()
            center = (box.GetMax() + box.GetMin()) * 0.5
            self._center_offsets[path] = (float(center[0]) - float(t[0]), float(center[1]) - float(t[1]))
        off = self._center_offsets[path]
        return float(t[0]) + off[0], float(t[1]) + off[1]

    def _try_grab_object(self):
        from pxr import Usd, UsdPhysics

        if getattr(self, "held_object", None):
            return
        gt = self._ground_truth_pose()
        if gt is None:
            return
        bx, by, byaw = gt
        gx, gy = self._gripper_world_point()
        cos_y, sin_y = math.cos(byaw), math.sin(byaw)
        best = None
        root = self.stage.GetPrimAtPath("/World/CompetitionObjects")
        if not root.IsValid():
            return

        for prim in root.GetChildren():
            cx, cy = self._object_center(prim)
            # Object position in the robot frame: rectangular grip zone.
            fwd = (cx - bx) * cos_y + (cy - by) * sin_y
            lat = -(cx - bx) * sin_y + (cy - by) * cos_y
            if (self.GRIP_ZONE_FWD_MIN_M <= fwd <= self.GRIP_ZONE_FWD_MAX_M
                    and abs(lat) <= self.GRIP_ZONE_LAT_M):
                dist = math.hypot(cx - gx, cy - gy)
                if best is None or dist < best[0]:
                    best = (dist, prim)
        if best is None:
            # Diagnose misses: where was the nearest object relative to the
            # gripper when CLOSE found nothing in reach?
            nearest = None
            for prim in root.GetChildren():
                cx, cy = self._object_center(prim)
                d = math.hypot(cx - gx, cy - gy)
                if nearest is None or d < nearest[0]:
                    nearest = (d, prim.GetName(), round(cx - gx, 3), round(cy - gy, 3))
            if nearest:
                self.node.get_logger().warn(
                    f"grip MISS: nearest {nearest[1]} at {nearest[0]:.3f}m "
                    f"(dx={nearest[2]}, dy={nearest[3]} world)"
                )
            return
        _, prim = best
        for target in [prim, *Usd.PrimRange(prim)]:
            if target.HasAPI(UsdPhysics.RigidBodyAPI):
                target.GetAttribute("physics:kinematicEnabled").Set(True)
            # Disable collisions while carried: the kinematic body follows the
            # gripper and would otherwise fight the robot's own colliders.
            if target.HasAPI(UsdPhysics.CollisionAPI):
                UsdPhysics.CollisionAPI(target).CreateCollisionEnabledAttr(False)
        self.held_object = str(prim.GetPath())
        self.node.get_logger().info(f"cheat-grip: grabbed {self.held_object}")

    RELEASE_FORWARD_M = 0.035   # clear of the gripper backstop wall
    RELEASE_REST_Z_M = 0.093    # just above the 8 cm object's rest height

    def _release_object(self):
        from pxr import Gf, Usd, UsdGeom, UsdPhysics

        held = getattr(self, "held_object", None)
        if not held:
            return
        prim = self.stage.GetPrimAtPath(held)
        if prim.IsValid():
            # Re-enabling collision while the carried object overlaps the
            # backstop/fingers makes PhysX resolve a deep penetration with a
            # violent impulse (objects were shot through the floor). Teleport
            # to a clear rest pose FIRST, then restore physics.
            gt = self._ground_truth_pose()
            if gt is not None:
                x, y, yaw = gt
                release_x = x + math.cos(yaw) * (self.GRIP_FORWARD_OFFSET_M + self.RELEASE_FORWARD_M)
                release_y = y + math.sin(yaw) * (self.GRIP_FORWARD_OFFSET_M + self.RELEASE_FORWARD_M)
                # Stacking: if another object already occupies the release
                # spot, rest on top of it instead of inside it.
                release_z = self.RELEASE_REST_Z_M
                root = self.stage.GetPrimAtPath("/World/CompetitionObjects")
                if root.IsValid():
                    for other in root.GetChildren():
                        if str(other.GetPath()) == held:
                            continue
                        ox_, oy_ = self._object_center(other)
                        if math.hypot(ox_ - release_x, oy_ - release_y) < 0.07:
                            release_z = self.RELEASE_REST_Z_M + 0.085
                            break
                xform = UsdGeom.Xformable(prim)
                for op in xform.GetOrderedXformOps():
                    if op.GetOpName() == "xformOp:translate":
                        # translate value == geometry center (pivotFix bake).
                        op.Set(Gf.Vec3d(release_x, release_y, release_z))
                        break
            for target in [prim, *Usd.PrimRange(prim)]:
                if target.HasAPI(UsdPhysics.RigidBodyAPI):
                    target.GetAttribute("physics:kinematicEnabled").Set(False)
                if target.HasAPI(UsdPhysics.CollisionAPI):
                    UsdPhysics.CollisionAPI(target).CreateCollisionEnabledAttr(True)
        self.node.get_logger().info(f"cheat-grip: released {held}")
        self.held_object = None

    def _update_held_object(self):
        from pxr import Gf, UsdGeom

        held = getattr(self, "held_object", None)
        if not held:
            return
        prim = self.stage.GetPrimAtPath(held)
        if not prim.IsValid():
            self.held_object = None
            return
        gx, gy = self._gripper_world_point()
        xform = UsdGeom.Xformable(prim)
        translate_op = None
        for op in xform.GetOrderedXformOps():
            if op.GetOpName() == "xformOp:translate":
                translate_op = op
                break
        if translate_op is None:
            translate_op = xform.AddTranslateOp(precision=UsdGeom.XformOp.PrecisionDouble)
        # Under the pivotFix bake the translate op value IS the geometry
        # center's world position - write the target directly. (The cached
        # offset is only for READS: matrix origin -> center.)
        translate_op.Set(Gf.Vec3d(gx, gy, self.GRIP_CARRY_HEIGHT_M))

    def _ground_truth_pose(self):
        if self.articulation is None:
            # Kinematic drive: the integrated bridge pose IS ground truth.
            return self.x, self.y, self.yaw
        positions, orientations = self.articulation.get_world_poses()
        p = self._to_list(positions)
        q = self._to_list(orientations)[:4]
        yaw = math.atan2(2.0 * (q[0] * q[3] + q[1] * q[2]), 1.0 - 2.0 * (q[2] ** 2 + q[3] ** 2))
        return p[0], p[1], yaw - math.radians(USD_VISUAL_YAW_OFFSET_DEG)

    def _gripper_joint_callback(self, msg):
        if not msg.position:
            return
        travel = float(msg.position[0])
        if math.isfinite(travel):
            self.gripper_travel = max(0.0, min(GRIPPER_OPEN_TRAVEL_M, abs(travel)))

    def _scan_callback(self, msg):
        msg.header.stamp = self._stamp()
        msg.header.frame_id = LIDAR_FRAME
        self.scan_pub.publish(msg)

    def _match_state_callback(self, msg):
        try:
            payload = json.loads(msg.data)
            self.match_state = str(payload.get("state", "?"))
            if payload.get("targets_label"):
                self._targets_label = str(payload["targets_label"])[:48]
            if payload.get("target_prims"):
                # Live circles: keep the prim names and resolve their CURRENT
                # centers at every snapshot (targets move once collected).
                self._target_prim_names = set(payload["target_prims"])
        except (ValueError, AttributeError):
            self.match_state = str(msg.data)[:24]
        # Zero the match clock when the runner comes alive (first state msg):
        # sim time starts at scene play, ~15s before the ROS stack is ready.
        if getattr(self, "match_t0", None) is None:
            self.match_t0 = self.sim_time

    def enable_snapshots(self, period_sim_s: float, out_dir: Path):
        self.snapshot_period = float(period_sim_s)
        self.snapshot_dir = out_dir
        out_dir.mkdir(parents=True, exist_ok=True)
        self._next_snapshot_time = self.sim_time

    def _update_snapshots(self):
        """Every N sim-seconds: top-view capture with match-clock (top-left)
        and robot state (top-right) burned in. For live progress checking."""
        if self.snapshot_period <= 0.0 or self.snapshot_dir is None:
            return
        # Annotate captures whose files have landed (capture is async).
        from PIL import Image, ImageDraw

        still_pending = []
        for path, time_label, state_label, circles in self._pending_annotations:
            if path.exists():
                try:
                    image = Image.open(str(path)).convert("RGB")
                    draw = ImageDraw.Draw(image)
                    draw.rectangle([0, 0, image.width, 26], fill=(0, 0, 0))
                    draw.text((8, 6), time_label, fill=(255, 255, 80))
                    label = getattr(self, "_targets_label", "")
                    if label:
                        draw.text(((image.width - 8 * len(label)) // 2, 6), label, fill=(255, 170, 60))
                    draw.text((image.width - 8 * len(state_label) - 12, 6), state_label, fill=(120, 255, 120))
                    # World->pixel for the fixed top view (eye z=7.2, 60 deg
                    # HFOV): ~116.2 px/m, +x right, +y up, centered.
                    for cx, cy in circles or []:
                        u = image.width / 2 + cx * 116.2
                        v = image.height / 2 - cy * 116.2
                        draw.ellipse([u - 18, v - 18, u + 18, v + 18], outline=(255, 40, 40), width=4)
                    image.save(str(path))
                except OSError:
                    still_pending.append((path, time_label, state_label, circles))
            else:
                still_pending.append((path, time_label, state_label, circles))
        self._pending_annotations = still_pending

        if self.sim_time < self._next_snapshot_time:
            return
        self._next_snapshot_time = self.sim_time + self.snapshot_period
        from omni.kit.viewport.utility import capture_viewport_to_file, get_active_viewport

        if not self._snapshot_camera_ready:
            from isaacsim.core.utils.viewports import set_camera_view

            viewport = get_active_viewport()
            viewport.set_texture_resolution([960, 960])
            set_camera_view(eye=[0.0, -0.01, 7.2], target=[0.0, 0.0, 0.0], camera_prim_path="/OmniverseKit_Persp")
            self._snapshot_camera_ready = True
        match_s = max(0.0, self.sim_time - (getattr(self, "match_t0", None) or self.sim_time))
        time_label = f"match {int(match_s // 60):02d}:{match_s % 60:04.1f}"
        path = self.snapshot_dir / f"t{match_s:07.1f}s.png"
        capture_viewport_to_file(get_active_viewport(), str(path))
        # Red circles on the targets' CURRENT positions in EVERY snapshot
        # (originally first-frame only; live tracking requested 2026-07-07).
        circles = None
        names = getattr(self, "_target_prim_names", None)
        if names:
            root = self.stage.GetPrimAtPath("/World/CompetitionObjects")
            circles = [self._object_center(prim)
                       for prim in (root.GetChildren() if root.IsValid() else [])
                       if prim.GetName() in names]
        self._pending_annotations.append((path, time_label, self.match_state, circles))

    # --- move_relative controller ---------------------------------------
    def _move_relative_twist(self, now: float) -> tuple[float, float, float] | None:
        if self.move_target is None:
            return None
        target_x, target_y, target_yaw, started = self.move_target
        if now - started > MOVE_RELATIVE_TIMEOUT_SEC:
            self._finish_move(ok=False, reason="timeout")
            return (0.0, 0.0, 0.0)
        # Stall guard on PROGRESS TOWARD THE TARGET (not raw motion): a
        # target beyond the wall clamp makes the robot slide ALONG the wall
        # - position changes but the target never gets closer, and the
        # protruding gripper (+0.245 m past base center) sweeps whatever is
        # beside the wall (fuse3 73-77 s: storage pins).
        dist_to_target = math.hypot(target_x - self.x, target_y - self.y) + abs(
            normalize_angle(target_yaw - self.yaw)
        )
        progress = getattr(self, "_move_progress", None)
        if progress is None or dist_to_target < progress[1] - 0.005:
            self._move_progress = (now, dist_to_target)
        elif now - progress[0] > 2.0:
            self._move_progress = None
            self._finish_move(ok=False, reason="stalled")
            return (0.0, 0.0, 0.0)
        err_x_world = target_x - self.x
        err_y_world = target_y - self.y
        err_yaw = normalize_angle(target_yaw - self.yaw)
        cos_yaw = math.cos(self.yaw)
        sin_yaw = math.sin(self.yaw)
        err_x = err_x_world * cos_yaw + err_y_world * sin_yaw
        err_y = -err_x_world * sin_yaw + err_y_world * cos_yaw
        physics = self.drive_mode == "physics"
        gain = MOVE_RELATIVE_GAIN_PHYSICS if physics else MOVE_RELATIVE_GAIN
        xy_tol = MOVE_RELATIVE_XY_TOLERANCE_PHYSICS_M if physics else MOVE_RELATIVE_XY_TOLERANCE_M
        if math.hypot(err_x, err_y) <= xy_tol and abs(err_yaw) <= MOVE_RELATIVE_YAW_TOLERANCE_RAD:
            self._finish_move(ok=True, reason="done")
            return (0.0, 0.0, 0.0)
        # max_v both lowers (fine-approach creep) and raises (long street
        # legs) the default; 0.75 m/s bounds it inside the motor envelope.
        cap = getattr(self, "move_speed_cap", None)
        v_cap = min(cap, 0.75) if cap else MOVE_RELATIVE_MAX_LINEAR_MPS
        vx = max(min(gain * err_x, v_cap), -v_cap)
        vy = max(min(gain * err_y, v_cap), -v_cap)
        wz = max(min(gain * err_yaw, MOVE_RELATIVE_MAX_ANGULAR_RPS), -MOVE_RELATIVE_MAX_ANGULAR_RPS)
        return (vx, vy, wz)

    def _finish_move(self, ok: bool, reason: str):
        if self.move_target is None:
            return
        _, _, _, started = self.move_target
        self.move_target = None
        self._publish_move_result(ok=ok, reason=reason, elapsed=time.monotonic() - started)

    def _publish_move_result(self, ok: bool, reason: str, elapsed: float = 0.0):
        msg = self.String()
        msg.data = json.dumps({"ok": bool(ok), "reason": reason, "elapsed_sec": round(elapsed, 3)})
        self.move_result_pub.publish(msg)

    # --- helpers ---------------------------------------------------------
    def _stamp(self):
        sec = int(self.sim_time)
        nanosec = int((self.sim_time - sec) * 1_000_000_000)
        stamp = self.node.get_clock().now().to_msg()
        stamp.sec = sec
        stamp.nanosec = nanosec
        return stamp

    @staticmethod
    def _to_list(values) -> list[float]:
        if hasattr(values, "numpy"):
            values = values.numpy()
        if hasattr(values, "tolist"):
            values = values.tolist()
        flat: list[float] = []
        stack = list(values) if isinstance(values, (list, tuple)) else [values]
        for item in stack:
            if isinstance(item, (list, tuple)):
                flat.extend(float(v) for v in item)
            else:
                flat.append(float(item))
        return flat

    # --- per-frame update --------------------------------------------------
    def _physics_time(self) -> float:
        """Physics-accurate sim time.

        The wall-locked timeline runs ahead of physics when rendering is slow
        (the standalone loop runner steps physics a fixed dt per frame), so
        odometry dt and message stamps must come from the physics clock.
        """
        try:
            from isaacsim.core.simulation_manager import SimulationManager

            value = float(SimulationManager.get_simulation_time())
            if math.isfinite(value) and value > 0.0:
                return value
        except Exception:
            pass
        return float(self.timeline.get_current_time())

    def update(self):
        now = time.monotonic()
        physics_time = self._physics_time()
        physics_dt = physics_time - self.sim_time
        wall_dt = min(max(now - self.last_wall, 0.0), KINEMATIC_MAX_DT)
        dt = physics_dt if 0.0 < physics_dt <= KINEMATIC_MAX_DT else (0.0 if physics_dt <= 0.0 else KINEMATIC_MAX_DT)
        if self.drive_mode != "physics" and dt == 0.0:
            dt = wall_dt
        if not math.isfinite(dt) or dt < 0.0:
            dt = 0.0
        self.last_wall = now
        if math.isfinite(physics_time) and physics_time > self.sim_time:
            self.sim_time = physics_time
        else:
            self.sim_time += dt

        self.rclpy.spin_once(self.node, timeout_sec=0.0)

        move_twist = self._move_relative_twist(now)
        if self.e_stop:
            vx, vy, wz = 0.0, 0.0, 0.0
        elif move_twist is not None:
            vx, vy, wz = move_twist
        else:
            vx, vy, wz = self._select_cmd(now)
        vx, vy, wz = self.kinematics.clamp_body_twist(vx, vy, wz, MAX_WHEEL_RAD_S)
        self.commanded_twist = (vx, vy, wz)

        if self.drive_mode == "physics":
            self._drive_physics(vx, vy, wz, dt)
        else:
            self._drive_kinematic(vx, vy, wz, dt)

        self._update_held_object()
        self._publish_objects_state(now)
        self._publish_clock()
        # Publish decimation: the main loop is single-thread latency-bound, so
        # per-frame JSON serialization directly costs RTF. Odom keeps ~10 Hz
        # effective; joint/ground-truth ~7 Hz.
        self._frame_count = getattr(self, "_frame_count", 0) + 1
        if self._frame_count % 2 == 0:
            self._publish_odom()
        if self._frame_count % 3 == 0:
            self._publish_joint_states()
        # GT every frame: the runner's fresh_gt() gates every leg on the
        # next GT message; at %3 those waits cost ~7 s sim per match.
        self._publish_ground_truth()
        self._publish_motor_state(now)
        self._update_snapshots()

    def _drive_physics(self, vx: float, vy: float, wz: float, dt: float):
        if self.articulation is None:
            return
        ik = self.kinematics.body_to_wheels(vx, vy, wz)
        targets = [[sign * value for sign, value in zip(WHEEL_JOINT_SIGNS, ik)]]
        self.articulation.set_dof_velocity_targets(targets, dof_indices=self.wheel_dof_indices)
        travel = max(0.0, min(GRIPPER_OPEN_TRAVEL_M, self.gripper_travel))
        self.articulation.set_dof_position_targets([[travel, travel]], dof_indices=self.finger_dof_indices)

        measured = self._to_list(self.articulation.get_dof_velocities(dof_indices=self.wheel_dof_indices))
        wheels = [sign * value for sign, value in zip(WHEEL_JOINT_SIGNS, measured)]
        self.wheel_velocities = wheels
        for index, value in enumerate(wheels):
            self.wheel_positions[index] += value * dt
        dx, dy, dyaw = self.kinematics.wheels_to_body(*(value * dt for value in wheels))
        midpoint_yaw = self.yaw + 0.5 * dyaw
        self.x += dx * math.cos(midpoint_yaw) - dy * math.sin(midpoint_yaw)
        self.y += dx * math.sin(midpoint_yaw) + dy * math.cos(midpoint_yaw)
        self.yaw = normalize_angle(self.yaw + dyaw)

    def _drive_kinematic(self, vx: float, vy: float, wz: float, dt: float):
        from pxr import Gf, UsdGeom

        ik = self.kinematics.body_to_wheels(vx, vy, wz)
        self.wheel_velocities = list(ik)
        for index, value in enumerate(ik):
            self.wheel_positions[index] += value * dt

        self.yaw = normalize_angle(self.yaw + wz * dt)
        cos_yaw = math.cos(self.yaw)
        sin_yaw = math.sin(self.yaw)
        self.x += (vx * cos_yaw - vy * sin_yaw) * dt
        self.y += (vx * sin_yaw + vy * cos_yaw) * dt
        # Walls are physical: the kinematic robot must not teleport through
        # them when a bad anchor commands an outward move (fuse2 released an
        # object at y=-2.21, outside the arena). The limit uses the FULL
        # footprint including the gripper protrusion (+0.245 m past base
        # center, projected on the world axes by the current heading), not
        # just the body half-extent - base-only clamping let the gripper
        # overhang the wall line and sweep objects beside it.
        tip_x = abs(math.cos(self.yaw)) * 0.245
        tip_y = abs(math.sin(self.yaw)) * 0.245
        limit_x = 2.0 - max(0.16, tip_x + 0.02)
        limit_y = 2.0 - max(0.16, tip_y + 0.02)
        self.x = max(-limit_x, min(limit_x, self.x))
        self.y = max(-limit_y, min(limit_y, self.y))

        xform = UsdGeom.Xformable(self.robot_prim)
        translate_op = None
        rotate_op = None
        for op in xform.GetOrderedXformOps():
            if op.GetOpName() == "xformOp:translate":
                translate_op = op
            elif op.GetOpName() == "xformOp:rotateZ":
                rotate_op = op
        if translate_op is None:
            translate_op = xform.AddTranslateOp()
        if rotate_op is None:
            rotate_op = xform.AddRotateZOp()
        translate_op.Set(Gf.Vec3d(self.x, self.y, START_XYZ[2]))
        rotate_op.Set(math.degrees(self.yaw) + USD_VISUAL_YAW_OFFSET_DEG)

    # --- publishers --------------------------------------------------------
    def _publish_clock(self):
        msg = self.Clock()
        msg.clock = self._stamp()
        self.clock_pub.publish(msg)

    def _publish_odom(self):
        stamp = self._stamp()
        vx, vy, wz = self.kinematics.wheels_to_body(*self.wheel_velocities)
        sin_half = math.sin(self.yaw * 0.5)
        cos_half = math.cos(self.yaw * 0.5)

        odom = self.Odometry()
        odom.header.stamp = stamp
        odom.header.frame_id = ODOM_FRAME
        odom.child_frame_id = BASE_FRAME
        odom.pose.pose.position.x = self.x
        odom.pose.pose.position.y = self.y
        odom.pose.pose.orientation.z = sin_half
        odom.pose.pose.orientation.w = cos_half
        odom.twist.twist.linear.x = vx
        odom.twist.twist.linear.y = vy
        odom.twist.twist.angular.z = wz
        self.odom_pub.publish(odom)
        self.odom_alias_pub.publish(odom)

        tf = self.TransformStamped()
        tf.header.stamp = stamp
        tf.header.frame_id = ODOM_FRAME
        tf.child_frame_id = BASE_FRAME
        tf.transform.translation.x = self.x
        tf.transform.translation.y = self.y
        tf.transform.rotation.z = sin_half
        tf.transform.rotation.w = cos_half
        self.tf_broadcaster.sendTransform(tf)

    def _publish_joint_states(self):
        msg = self.JointState()
        msg.header.stamp = self._stamp()
        msg.name = list(WHEEL_DOF_NAMES) + list(FINGER_DOF_NAMES)
        msg.position = list(self.wheel_positions) + [self.gripper_travel, self.gripper_travel]
        msg.velocity = list(self.wheel_velocities) + [0.0, 0.0]
        self.joint_pub.publish(msg)

    def _publish_motor_state(self, now: float):
        if now - self._motor_state_last_pub < 0.1:
            return
        self._motor_state_last_pub = now
        vx, vy, wz = self.commanded_twist
        msg = self.String()
        msg.data = json.dumps(
            {
                "drive_type": "mecanum",
                "connected": True,
                "sim": True,
                "mode": "position" if self.move_target is not None else "velocity",
                "e_stop": self.e_stop,
                "commanded_velocity": {"linear_x": vx, "linear_y": vy, "angular_z": wz},
                "wheels": {
                    name: {"rad_s": round(self.wheel_velocities[index], 4)}
                    for index, name in enumerate(WHEEL_NAMES)
                },
                "odom": {"x": round(self.x, 4), "y": round(self.y, 4), "yaw": round(self.yaw, 4)},
                "geometry": {
                    "wheel_radius_m": WHEEL_RADIUS_M,
                    "half_length_m": HALF_LENGTH_M,
                    "half_width_m": HALF_WIDTH_M,
                },
            }
        )
        self.motor_state_pub.publish(msg)
        state = self.String()
        state.data = json.dumps(
            {
                "state": "open" if self.gripper_travel > 0.5 * GRIPPER_OPEN_TRAVEL_M else "closed",
                "held_object": getattr(self, "held_object", None),
                "travel_m": round(self.gripper_travel, 4),
                "sim": True,
            }
        )
        self.gripper_state_pub.publish(state)

    def _publish_objects_state(self, now: float):
        """1 Hz judge's-eye view: object poses + top-down rim containment."""
        if now - self._objects_state_last_pub < 1.0:
            return
        self._objects_state_last_pub = now
        import omni.usd

        root = self.stage.GetPrimAtPath("/World/CompetitionObjects")
        if not root.IsValid():
            return
        xmin, xmax, ymin, ymax = STORAGE_ZONE
        h = OBJECT_HALF_EXTENT_M
        items = []
        scored = 0
        for prim in root.GetChildren():
            matrix = omni.usd.get_world_transform_matrix(prim)
            t = matrix.ExtractTranslation()
            x, y = self._object_center(prim)
            z = float(t[2])
            in_storage = (xmin + h <= x <= xmax - h) and (ymin + h <= y <= ymax - h)
            scored += bool(in_storage)
            items.append(
                {
                    "prim": prim.GetName(),
                    "x": round(x, 3),
                    "y": round(y, 3),
                    "z": round(z, 3),
                    "in_storage": in_storage,
                    "held": str(prim.GetPath()) == getattr(self, "held_object", None),
                }
            )
        msg = self.String()
        msg.data = json.dumps({"scored_in_storage": scored, "objects": items})
        self.objects_state_pub.publish(msg)

    def _publish_ground_truth(self):
        if self.articulation is not None:
            # Physics poses live in Fabric, not the USD xform ops; read the
            # articulation root pose through the physics tensor API.
            positions, orientations = self.articulation.get_world_poses()
            position = self._to_list(positions)
            qw, qx, qy, qz = self._to_list(orientations)[:4]
            quat_yaw = math.atan2(2.0 * (qw * qz + qx * qy), 1.0 - 2.0 * (qy * qy + qz * qz))
            translation = (position[0], position[1], position[2])
            yaw = quat_yaw - math.radians(USD_VISUAL_YAW_OFFSET_DEG)
        else:
            import omni.usd

            matrix = omni.usd.get_world_transform_matrix(self.robot_prim)
            translation = matrix.ExtractTranslation()
            rotation = matrix.ExtractRotation()
            axis = rotation.GetAxis()
            angle_deg = rotation.GetAngle() * (1.0 if axis[2] >= 0 else -1.0)
            yaw = math.radians(angle_deg) - math.radians(USD_VISUAL_YAW_OFFSET_DEG)
        msg = self.String()
        msg.data = json.dumps(
            {
                "x": round(float(translation[0]), 4),
                "y": round(float(translation[1]), 4),
                "z": round(float(translation[2]), 4),
                "yaw": round(normalize_angle(yaw), 4),
                "sim_time": round(self.sim_time, 4),
                "odom": {"x": round(self.x, 4), "y": round(self.y, 4), "yaw": round(self.yaw, 4)},
            }
        )
        self.ground_truth_pub.publish(msg)
        self._publish_imu(float(translation[0]), float(translation[1]), normalize_angle(yaw))

    def _publish_imu(self, x: float, y: float, yaw: float):
        """Synthetic D435i IMU from TRUE pose derivatives (slip-free, like a
        real gyro). Noise/bias follow the BMI055 datasheet; the publish rate
        is the sim loop rate, so white noise scales with the actual dt."""
        prev = self._imu_prev
        now_s = self.sim_time
        if prev is None:
            self._imu_prev = (now_s, x, y, yaw, 0.0, 0.0)
            return
        dt = now_s - prev[0]
        if dt <= 1e-5 or dt > 0.5:
            self._imu_prev = (now_s, x, y, yaw, prev[4], prev[5])
            return
        wz_true = math.atan2(math.sin(yaw - prev[3]), math.cos(yaw - prev[3])) / dt
        vx_w = (x - prev[1]) / dt
        vy_w = (y - prev[2]) / dt
        ax_w = (vx_w - prev[4]) / dt
        ay_w = (vy_w - prev[5]) / dt
        self._imu_prev = (now_s, x, y, yaw, vx_w, vy_w)

        sigma_g = IMU_GYRO_NOISE_DENSITY_RAD * math.sqrt(0.5 / dt)
        gyro_z = wz_true + self._imu_gyro_bias + self._imu_rand.gauss(0.0, sigma_g)
        gyro_z = max(-IMU_GYRO_RANGE_RAD_S, min(IMU_GYRO_RANGE_RAD_S, gyro_z))
        sigma_a = IMU_ACCEL_NOISE_DENSITY * math.sqrt(0.5 / dt)
        cos_y, sin_y = math.cos(yaw), math.sin(yaw)
        ax_b = ax_w * cos_y + ay_w * sin_y + self._imu_rand.gauss(0.0, sigma_a)
        ay_b = -ax_w * sin_y + ay_w * cos_y + self._imu_rand.gauss(0.0, sigma_a)
        az_b = 9.81 + self._imu_rand.gauss(0.0, sigma_a)

        imu = self.Imu()
        imu.header.stamp = self._stamp()
        imu.header.frame_id = "d435i_imu_link"
        imu.orientation_covariance[0] = -1.0  # no orientation, like the real driver
        imu.angular_velocity.z = gyro_z
        imu.angular_velocity_covariance[8] = sigma_g * sigma_g
        imu.linear_acceleration.x = max(-IMU_ACCEL_RANGE, min(IMU_ACCEL_RANGE, ax_b))
        imu.linear_acceleration.y = max(-IMU_ACCEL_RANGE, min(IMU_ACCEL_RANGE, ay_b))
        imu.linear_acceleration.z = max(-IMU_ACCEL_RANGE, min(IMU_ACCEL_RANGE, az_b))
        imu.linear_acceleration_covariance[0] = sigma_a * sigma_a
        self.imu_pub.publish(imu)

    def shutdown(self):
        self.node.destroy_node()


def run_demo(app: SimulationApp, scene: Path, run_seconds: float = 0.0) -> None:
    """Loop the DEMO_SEQUENCE by writing wheel IK targets directly.

    Deliberately creates NO ROS node/publisher: safe to run alongside other
    ROS work on the machine.
    """
    import omni.timeline
    import omni.usd

    context = omni.usd.get_context()
    if not context.open_stage(str(scene)):
        raise RuntimeError(f"Failed to open generated scene: {scene}")
    for _ in range(60):
        app.update()
    omni.timeline.get_timeline_interface().play()
    for _ in range(10):
        app.update()

    from isaacsim.core.experimental.prims import Articulation
    from isaacsim.core.simulation_manager import SimulationManager

    robot = Articulation(ROBOT_ROOT)
    wheel_idx = robot.get_dof_indices(list(WHEEL_DOF_NAMES))
    kinematics = MecanumKinematics(WHEEL_RADIUS_M, HALF_LENGTH_M, HALF_WIDTH_M)

    def sim_now() -> float:
        return float(SimulationManager.get_simulation_time())

    print("[demo] mecanum showcase loop started (no ROS node created)", flush=True)
    wall_start = time.monotonic()
    cycle = 0
    while app.is_running():
        cycle += 1
        for label, (vx, vy, wz), duration in DEMO_SEQUENCE:
            if not app.is_running():
                break
            ik = kinematics.body_to_wheels(vx, vy, wz)
            targets = [[sign * value for sign, value in zip(WHEEL_JOINT_SIGNS, ik)]]
            print(
                f"[demo] cycle {cycle}: {label:20s} twist=({vx:+.2f},{vy:+.2f},{wz:+.2f}) "
                f"wheels(FL,FR,RL,RR)=({ik[0]:+.2f},{ik[1]:+.2f},{ik[2]:+.2f},{ik[3]:+.2f}) rad/s",
                flush=True,
            )
            phase_end = sim_now() + duration
            while app.is_running() and sim_now() < phase_end:
                robot.set_dof_velocity_targets(targets, dof_indices=wheel_idx)
                app.update()
            if run_seconds > 0 and time.monotonic() - wall_start >= run_seconds:
                return


def main() -> int:
    args = parse_args()
    os.environ["ROS_DISTRO"] = args.ros_distro
    app = SimulationApp({"headless": bool(args.headless)})
    try:
        from isaacsim.asset.importer.urdf import URDFImporter, URDFImporterConfig
        from isaacsim.core.utils.extensions import enable_extension

        for extension in (
            "isaacsim.asset.importer.urdf",
            "isaacsim.ros2.bridge",
            "isaacsim.sensors.physx",
        ):
            try:
                enable_extension(extension)
            except Exception:
                pass
        for _ in range(30):
            app.update()

        stadium = Path(args.stadium).expanduser().resolve()
        urdf = Path(args.urdf).expanduser().resolve()
        usd_dir = Path(args.usd_dir).expanduser().resolve()
        scene = Path(args.scene).expanduser().resolve()
        proof_path = Path(args.proof_path).expanduser().resolve()

        require_path(stadium, "stadium USD")
        require_path(urdf, "robot URDF")
        load_urdf_geometry(urdf)
        if args.speed_scale != 1.0:
            global MAX_LINEAR_X_MPS, MAX_LINEAR_Y_MPS, MAX_ANGULAR_RPS, MAX_WHEEL_RAD_S
            global MOVE_RELATIVE_MAX_LINEAR_MPS, MOVE_RELATIVE_MAX_ANGULAR_RPS
            MAX_LINEAR_X_MPS *= args.speed_scale
            MAX_LINEAR_Y_MPS *= args.speed_scale
            MAX_ANGULAR_RPS *= args.speed_scale
            MAX_WHEEL_RAD_S *= args.speed_scale
            MOVE_RELATIVE_MAX_LINEAR_MPS *= args.speed_scale
            MOVE_RELATIVE_MAX_ANGULAR_RPS *= args.speed_scale
            print(
                f"speed scale {args.speed_scale}: caps vx={MAX_LINEAR_X_MPS:.2f} "
                f"vy={MAX_LINEAR_Y_MPS:.2f} wz={MAX_ANGULAR_RPS:.2f} wheel={MAX_WHEEL_RAD_S:.1f}",
                flush=True,
            )
        if args.overwrite and usd_dir.exists():
            shutil.rmtree(usd_dir)
        usd_dir.mkdir(parents=True, exist_ok=True)
        scene.parent.mkdir(parents=True, exist_ok=True)

        import_config = URDFImporterConfig(
            urdf_path=str(urdf),
            usd_path=str(usd_dir),
            collision_from_visuals=False,
            merge_fixed_joints=False,
            merge_mesh=True,
            fix_base=False,
            allow_self_collision=False,
            joint_drive_type={
                ".*wheel_spin": "force",
                ".*finger.*": "force",
            },
            joint_target_type={
                ".*roller.*": "none",
                ".*wheel_spin": "velocity",
                ".*finger.*": "position",
            },
            override_joint_stiffness={
                ".*roller.*": 0.0,
                ".*wheel_spin": 0.0,
                ".*finger.*": 800.0,
            },
            override_joint_damping={
                ".*roller.*": 0.0,
                ".*wheel_spin": 50.0,
                ".*finger.*": 60.0,
            },
            ros_package_paths=[
                {"robot_description": str(REPO_ROOT / "src" / "robot_description")},
            ],
        )
        robot_usd = Path(URDFImporter(import_config).import_urdf()).resolve()
        require_path(robot_usd, "imported robot USD")

        # The importer authors visuals as purpose="guide"; flip them so the
        # chassis/gripper/sensor bodies actually render (mk2 flow does this too).
        import create_mobile_manipulator_scene as mobile_scene

        renderable_robot_assets = mobile_scene.make_robot_collision_primitives_renderable(robot_usd)

        write_composed_scene(scene, stadium, robot_usd, kinematic_root=(args.drive_mode == "kinematic"))
        require_path(scene, "composed scene USD")

        # Reuse the camera builders from the diff-drive scene script, but
        # attach sensors to rigid-body LINK prims (NOT the USD root): the
        # physics articulation moves through Fabric, so only prims under a
        # link follow the robot. The lidar goes on the URDF lidar link (small
        # body, CoM == frame origin) so the PhysX sensor pose is exact.
        lidar_parent = f"{ROBOT_ROOT}/Geometry/base_link/lidar"
        mobile_scene.ROBOT_ROOT = f"{ROBOT_ROOT}/Geometry/base_link"

        # Real-robot camera mounts, mast DOWN, per the 2026-07-16 field
        # calibration (71_scan_grid_snap_analysis.py TOP_MOUNT: grid-search
        # fit over 8 ground-truth objects -> mean error 7.5 cm, snap 7/7;
        # cross-check near 0.268 + 0.10 inter-cam offset = 0.368 ~ 0.360).
        # The old nominal top mount 0.2925 m / 19 deg carries a 25 cm ground
        # projection error on the real robot - do not resurrect it. Mast UP
        # has no fitted calibration yet; model it with --camera-z-offset
        # (assumed +0.20 m pure vertical lift of both cameras).
        real_mounts = {"camera_19deg_optical_frame": ((0.0, 0.198, 0.360), 18.5),
                       "camera_54deg_optical_frame": ((0.0, 0.1874, 0.2680), 54.0)}
        mobile_scene.CAMERA_SPECS = [
            {**spec,
             "xyz": (real_mounts[spec["name"]][0][0], real_mounts[spec["name"]][0][1],
                     real_mounts[spec["name"]][0][2] + args.camera_z_offset),
             "tilt_deg": real_mounts[spec["name"]][1]}
            if spec["name"] in real_mounts else spec
            for spec in mobile_scene.CAMERA_SPECS
        ]
        if args.camera_z_offset != 0.0:
            print(f"camera z offset applied: +{args.camera_z_offset} m", flush=True)
        camera_publishers = [] if args.no_cameras else mobile_scene.configure_camera_publishers(scene, app)
        hidden_camera_placeholders = mobile_scene.hide_urdf_camera_placeholders(scene, app)
        # Slightly below the lidar link origin: scan plane ~0.32 m above the
        # floor - above the 0.17 m objects, below the 0.35 m wall tops.
        lidar_publisher = configure_mecanum_lidar(
            scene, app, parent_prim=lidar_parent, translation=(0.0, 0.0, -0.01), yaw_deg=90.0
        )
        physics_tuning = tune_physics(scene, app)

        proof = {
            "ok": True,
            "scene": str(scene),
            "stadium": str(stadium),
            "urdf": str(urdf),
            "robot_usd": str(robot_usd),
            "robot_prim": ROBOT_ROOT,
            "drive_mode": args.drive_mode,
            "start_pose": {
                "x": START_XYZ[0],
                "y": START_XYZ[1],
                "z": START_XYZ[2],
                "yaw_deg": START_YAW_DEG,
            },
            "wheel_dof_names": list(WHEEL_DOF_NAMES),
            "wheel_joint_signs": list(WHEEL_JOINT_SIGNS),
            "geometry": {
                "wheel_radius_m": WHEEL_RADIUS_M,
                "half_length_m": HALF_LENGTH_M,
                "half_width_m": HALF_WIDTH_M,
            },
            "camera_publishers": camera_publishers,
            "hidden_camera_placeholders": hidden_camera_placeholders,
            "lidar_publisher": lidar_publisher,
            "physics_tuning": physics_tuning,
            "ros_contract": {
                "cmd_vel": CMD_VEL_TOPIC,
                "cmd_vel_direct": CMD_VEL_DIRECT_TOPIC,
                "move_relative": MOVE_RELATIVE_TOPIC,
                "move_result": MOVE_RESULT_TOPIC,
                "odom": ODOM_TOPIC,
                "odom_alias": ODOM_ALIAS_TOPIC,
                "motor_state": MOTOR_STATE_TOPIC,
                "scan": LIDAR_TOPIC,
                "gripper_command": GRIPPER_STRING_TOPIC,
                "gripper_joint_command": GRIPPER_COMMAND_TOPIC,
                "ground_truth": GROUND_TRUTH_TOPIC,
            },
        }
        proof_path.parent.mkdir(parents=True, exist_ok=True)
        proof_path.write_text(json.dumps(proof, indent=2, sort_keys=True), encoding="utf-8")
        print(json.dumps(proof, indent=2, sort_keys=True), flush=True)

        if args.demo:
            run_demo(app, scene, run_seconds=args.run_seconds)
            return 0

        if args.run:
            import omni.timeline
            import omni.usd

            context = omni.usd.get_context()
            if not context.open_stage(str(scene)):
                raise RuntimeError(f"Failed to open generated scene: {scene}")
            for _ in range(60):
                app.update()
            omni.timeline.get_timeline_interface().play()
            for _ in range(10):
                app.update()

            bridge = MecanumSimBridge(context.get_stage(), drive_mode=args.drive_mode)
            if args.drive_mode == "physics":
                bridge.attach_articulation()
            if args.snapshot_period > 0.0:
                stamp = time.strftime("%Y%m%d_%H%M%S")
                bridge.enable_snapshots(args.snapshot_period, REPO_ROOT / "logs" / "match_snapshots" / stamp)
                print(f"snapshots every {args.snapshot_period} sim-s -> logs/match_snapshots/{stamp}/", flush=True)
            print(
                json.dumps(
                    {
                        "ok": True,
                        "runtime_bridge": "mecanum_isaac_sim_bridge",
                        "drive_mode": args.drive_mode,
                        "subscribes": list(CMD_SOURCE_PRIORITY)
                        + [MOVE_RELATIVE_TOPIC, E_STOP_TOPIC, GRIPPER_STRING_TOPIC],
                        "publishes": ["/clock", ODOM_TOPIC, MOTOR_STATE_TOPIC, LIDAR_TOPIC, "/tf"],
                    },
                    indent=2,
                    sort_keys=True,
                ),
                flush=True,
            )
            start = time.monotonic()
            while app.is_running():
                bridge.update()
                app.update()
                if args.run_seconds > 0 and time.monotonic() - start >= args.run_seconds:
                    break
            bridge.shutdown()
        return 0
    finally:
        app.close()


if __name__ == "__main__":
    raise SystemExit(main())
